apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-application
  template:
    metadata:
      labels:
        app: example-application
    spec:
      containers:
      - image: TsenkoTsenkov/ApplicationExampleGitOps:v2
        name: ApplicationExampleGitOps
      - image: <image-name>:<tag>
        name: example-application
        port:
        - containerPort: 8080
